on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: touch file
        run: touch ${{inputs.name}}
      - name: ls
        run: ls -la
      - name: whoami
        run: whoami
