on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
      - run: echo ${{inputs.name}}
      - name: build with maven
        run: mvn --batch-mode --update-snapshots clean package
      - name: touch file
        run: touch aaa
      - name: ls
        run: ls -la
